insert into public.mountains (
  id,
  slug,
  name,
  province,
  island,
  elevation,
  latitude,
  longitude,
  summary,
  description,
  difficulty,
  beginner_score,
  duration_days,
  budget_category,
  best_season,
  sunrise_rating,
  camping_available,
  water_source,
  popularity_score,
  hero_image,
  status
)
values
  (
    '10000000-0000-4000-8000-000000000001',
    'gunung-semeru',
    'Gunung Semeru',
    'Jawa Timur',
    'Jawa',
    3657,
    -8.108000,
    112.922000,
    'Pendakian panjang menuju lanskap vulkanik tertinggi di Pulau Jawa.',
    'Gunung Semeru berada di kawasan Taman Nasional Bromo Tengger Semeru. Jalur Ranu Pani melewati hutan pegunungan dan Ranu Kumbolo sebelum medan vulkanik yang lebih terbuka. Informasi ini bersifat perencanaan; status buka, batas pendakian, cuaca, dan rekomendasi keselamatan wajib diperiksa ke pengelola resmi.',
    'extreme',
    18,
    3.0,
    'high',
    'Mei–September',
    4,
    true,
    true,
    98,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  ),
  (
    '10000000-0000-4000-8000-000000000002',
    'gunung-rinjani',
    'Gunung Rinjani',
    'Nusa Tenggara Barat',
    'Nusa Tenggara',
    3726,
    -8.420000,
    116.470000,
    'Trek multi-hari dengan punggungan terbuka dan panorama kaldera Segara Anak.',
    'Gunung Rinjani mendominasi Pulau Lombok dan memiliki jaringan jalur pendakian dari Sembalun, Senaru, serta titik resmi lain. Perjalanan menuju puncak dan kaldera membutuhkan kebugaran, aklimatisasi, logistik bermalam, dan pemeriksaan kuota serta status jalur terbaru.',
    'extreme',
    20,
    3.0,
    'high',
    'Juli–September',
    5,
    true,
    true,
    100,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  ),
  (
    '10000000-0000-4000-8000-000000000003',
    'gunung-kerinci',
    'Gunung Kerinci',
    'Jambi',
    'Sumatra',
    3800,
    -1.697000,
    101.264000,
    'Atap Sumatra dengan jalur hutan tropis yang panjang dari Kersik Tuo.',
    'Gunung Kerinci berada di Taman Nasional Kerinci Seblat. Jalur utama dari Kersik Tuo menanjak melalui hutan rapat menuju area terbuka dekat puncak. Pendakian ini menuntut pengalaman, pemandu lokal, serta pengecekan kondisi satwa, cuaca, dan aktivitas vulkanik.',
    'extreme',
    15,
    2.0,
    'high',
    'Mei–September',
    4,
    true,
    true,
    92,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  ),
  (
    '10000000-0000-4000-8000-000000000004',
    'gunung-merbabu',
    'Gunung Merbabu',
    'Jawa Tengah',
    'Jawa',
    3118,
    -7.454000,
    110.440000,
    'Punggungan sabana luas dengan pandangan langsung ke gunung-gunung Jawa Tengah.',
    'Gunung Merbabu memiliki beberapa jalur resmi, termasuk Selo dan Wekas. Jalur Selo dikenal dengan punggungan terbuka dan panorama Merapi, tetapi tetap panjang, curam, dan dapat licin. Registrasi, kuota, serta penutupan jalur perlu diperiksa sebelum berangkat.',
    'hard',
    42,
    2.0,
    'medium',
    'Mei–Oktober',
    5,
    true,
    false,
    94,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  ),
  (
    '10000000-0000-4000-8000-000000000005',
    'gunung-gede',
    'Gunung Gede',
    'Jawa Barat',
    'Jawa',
    2965,
    -6.789722,
    106.983333,
    'Trek hutan pegunungan menuju kawah, air panas, dan dataran tinggi Surya Kencana.',
    'Gunung Gede berada dalam kawasan Taman Nasional Gunung Gede Pangrango. Jalur Cibodas dan Gunung Putri menghubungkan hutan montana, air terjun, area berkemah, dan puncak. Medan tetap menuntut persiapan meski populer untuk pendaki yang sedang meningkatkan pengalaman.',
    'moderate',
    62,
    2.0,
    'medium',
    'Mei–September',
    4,
    true,
    true,
    91,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  ),
  (
    '10000000-0000-4000-8000-000000000006',
    'gunung-papandayan',
    'Gunung Papandayan',
    'Jawa Barat',
    'Jawa',
    2665,
    -7.320000,
    107.730000,
    'Kawah aktif, Hutan Mati, dan area kemah yang dapat dijangkau dalam perjalanan singkat.',
    'Gunung Papandayan menawarkan lanskap kawah, hutan mati, dan padang edelweis dalam kawasan wisata alam. Pilihan rute berbeda memiliki karakter dan panjang yang berbeda; pengunjung tetap harus mengikuti batas aman kawah dan arahan pengelola.',
    'easy',
    84,
    1.0,
    'low',
    'Mei–Oktober',
    4,
    true,
    true,
    86,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  ),
  (
    '10000000-0000-4000-8000-000000000007',
    'gunung-bromo',
    'Gunung Bromo',
    'Jawa Timur',
    'Jawa',
    2329,
    -7.942000,
    112.950000,
    'Pendekatan singkat melintasi lautan pasir menuju bibir kawah Tengger.',
    'Gunung Bromo adalah kerucut aktif di dalam Kaldera Tengger dan bagian dari Taman Nasional Bromo Tengger Semeru. Akses pejalan kaki menuju kawah relatif singkat, tetapi pengunjung harus mematuhi radius aman, cuaca, dan pembatasan resmi yang dapat berubah.',
    'easy',
    88,
    1.0,
    'medium',
    'Mei–September',
    5,
    false,
    false,
    99,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  ),
  (
    '10000000-0000-4000-8000-000000000008',
    'kawah-ijen',
    'Kawah Ijen',
    'Jawa Timur',
    'Jawa',
    2769,
    -8.058000,
    114.242000,
    'Pendakian dini hari menuju kaldera, danau asam, dan lanskap pertambangan belerang.',
    'Kompleks Ijen memiliki danau kawah asam dan aktivitas fumarola. Jalur wisata bermula dari Paltuding menuju bibir kawah. Gas vulkanik, arah angin, pembatasan turun ke kawah, dan status operasional harus dipastikan melalui otoritas setempat.',
    'moderate',
    67,
    1.0,
    'medium',
    'Mei–September',
    5,
    false,
    false,
    95,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  ),
  (
    '10000000-0000-4000-8000-000000000009',
    'gunung-batur',
    'Gunung Batur',
    'Bali',
    'Bali',
    1711,
    -8.240300,
    115.377500,
    'Pendakian fajar populer dengan panorama kaldera dan Danau Batur.',
    'Gunung Batur berada di dalam kaldera besar di Kintamani. Jalur populer dapat ditempuh dalam setengah hari, tetapi permukaan vulkanik, keramaian, dan pendakian malam tetap membutuhkan perlengkapan, pemandu sesuai aturan lokal, dan pengecekan kondisi.',
    'moderate',
    70,
    1.0,
    'medium',
    'Juli–Oktober',
    5,
    false,
    false,
    97,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  ),
  (
    '10000000-0000-4000-8000-000000000010',
    'gunung-kelimutu',
    'Gunung Kelimutu',
    'Nusa Tenggara Timur',
    'Nusa Tenggara',
    1639,
    -8.770000,
    121.820000,
    'Jalur pendek menuju sudut pandang tiga danau kawah Kelimutu.',
    'Kelimutu di Pulau Flores dikenal karena tiga danau kawahnya. Akses utama dari area parkir taman nasional berupa jalur pejalan kaki yang relatif pendek, namun pagar, zona larangan, cuaca, dan arahan petugas wajib dipatuhi.',
    'easy',
    91,
    1.0,
    'low',
    'Mei–Oktober',
    5,
    false,
    false,
    83,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  ),
  (
    '10000000-0000-4000-8000-000000000011',
    'gunung-tambora',
    'Gunung Tambora',
    'Nusa Tenggara Barat',
    'Nusa Tenggara',
    2850,
    -8.250000,
    118.000000,
    'Ekspedisi multi-hari menuju bibir kaldera besar di Semenanjung Sanggar.',
    'Gunung Tambora membentuk sebagian besar Semenanjung Sanggar di Sumbawa. Jalur menuju kaldera panjang dan terpencil, sehingga memerlukan logistik, navigasi, pemandu, serta konfirmasi jalur dan aktivitas vulkanik terkini.',
    'extreme',
    12,
    3.0,
    'high',
    'Juni–Oktober',
    4,
    true,
    true,
    79,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  ),
  (
    '10000000-0000-4000-8000-000000000012',
    'gunung-prau',
    'Gunung Prau',
    'Jawa Tengah',
    'Jawa',
    2600,
    -7.194000,
    109.930000,
    'Pendakian singkat dan curam menuju area kemah dengan panorama matahari terbit.',
    'Gunung Prau berada di kawasan Dataran Tinggi Dieng. Jalur Patak Banteng populer karena relatif singkat, tetapi tanjakan, tanah lepas, suhu malam, dan kepadatan akhir pekan tetap perlu dipertimbangkan.',
    'moderate',
    78,
    1.0,
    'low',
    'Juni–September',
    5,
    true,
    false,
    90,
    '/images/mountains/placeholder-mountain.svg',
    'published'
  )
on conflict (slug) do update
set
  name = excluded.name,
  province = excluded.province,
  island = excluded.island,
  elevation = excluded.elevation,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  summary = excluded.summary,
  description = excluded.description,
  difficulty = excluded.difficulty,
  beginner_score = excluded.beginner_score,
  duration_days = excluded.duration_days,
  budget_category = excluded.budget_category,
  best_season = excluded.best_season,
  sunrise_rating = excluded.sunrise_rating,
  camping_available = excluded.camping_available,
  water_source = excluded.water_source,
  popularity_score = excluded.popularity_score,
  hero_image = excluded.hero_image,
  status = excluded.status,
  updated_at = now();

insert into public.mountain_routes (
  id,
  mountain_id,
  name,
  starting_point,
  distance_km,
  elevation_gain,
  estimated_hours,
  difficulty,
  facilities,
  description
)
values
  (
    '20000000-0000-4000-8000-000000000001',
    (select id from public.mountains where slug = 'gunung-semeru'),
    'Ranu Pani–Puncak Semeru',
    'Ranu Pani',
    31.90,
    2502,
    14.4,
    'extreme',
    'Pos registrasi, area kemah, dan sumber air musiman di koridor Ranu Kumbolo; ketersediaan wajib dikonfirmasi.',
    'Rute pergi-pulang dari Ranu Pani melalui Ranu Kumbolo dan koridor pendakian Semeru. Batas pendakian dapat berubah karena aktivitas vulkanik.'
  ),
  (
    '20000000-0000-4000-8000-000000000002',
    (select id from public.mountains where slug = 'gunung-rinjani'),
    'Sembalun–Senaru',
    'Desa Sembalun',
    36.70,
    3389,
    18.9,
    'extreme',
    'Pos registrasi, area kemah, porter dan pemandu lokal; sumber air bersifat musiman.',
    'Rute lintas dari Sembalun menuju puncak, Segara Anak, lalu keluar melalui Senaru. Umumnya direncanakan sebagai perjalanan multi-hari.'
  ),
  (
    '20000000-0000-4000-8000-000000000003',
    (select id from public.mountains where slug = 'gunung-kerinci'),
    'Kersik Tuo',
    'Kersik Tuo',
    17.90,
    2137,
    10.6,
    'extreme',
    'Basecamp, shelter, area kemah terbatas, dan sumber air dekat Pintu Rimba.',
    'Rute pergi-pulang melalui hutan Taman Nasional Kerinci Seblat dari Kersik Tuo menuju puncak.'
  ),
  (
    '20000000-0000-4000-8000-000000000004',
    (select id from public.mountains where slug = 'gunung-merbabu'),
    'Selo',
    'Selo, Boyolali',
    11.10,
    1341,
    7.0,
    'hard',
    'Basecamp, pos registrasi, area kemah, dan toilet di titik awal; air di jalur terbatas.',
    'Rute pergi-pulang dari Selo melalui sabana dan punggungan terbuka menuju area puncak Merbabu.'
  ),
  (
    '20000000-0000-4000-8000-000000000005',
    (select id from public.mountains where slug = 'gunung-gede'),
    'Cibodas',
    'Cibodas',
    17.70,
    1646,
    10.0,
    'hard',
    'Pos registrasi, shelter, area kemah, toilet di titik tertentu, dan sumber air di beberapa koridor.',
    'Rute pergi-pulang dari Cibodas melewati Telaga Biru, air panas, Kandang Badak, lalu puncak Gunung Gede.'
  ),
  (
    '20000000-0000-4000-8000-000000000006',
    (select id from public.mountains where slug = 'gunung-papandayan'),
    'Neglawangi',
    'Neglawangi',
    16.40,
    895,
    6.0,
    'hard',
    'Area parkir, loket, toilet, warung di titik awal, dan area kemah.',
    'Rute pergi-pulang menuju lanskap Papandayan melalui hutan, kawah, dan area sabana.'
  ),
  (
    '20000000-0000-4000-8000-000000000007',
    (select id from public.mountains where slug = 'gunung-bromo'),
    'B 49–Bromo',
    'B 49',
    6.00,
    205,
    1.8,
    'moderate',
    'Area parkir dan layanan wisata di kawasan Tengger; fasilitas di jalur terbatas.',
    'Rute pergi-pulang melintasi lanskap Tengger menuju kawasan Gunung Bromo.'
  ),
  (
    '20000000-0000-4000-8000-000000000008',
    (select id from public.mountains where slug = 'kawah-ijen'),
    'Paltuding–Bibir Kawah',
    'Paltuding',
    6.00,
    550,
    3.5,
    'moderate',
    'Loket, area parkir, toilet, warung musiman, dan penyewaan masker di Paltuding.',
    'Rute pergi-pulang dari Paltuding menuju bibir Kawah Ijen. Turun ke area kawah memiliki risiko tambahan dan tunduk pada pembatasan petugas.'
  ),
  (
    '20000000-0000-4000-8000-000000000009',
    (select id from public.mountains where slug = 'gunung-batur'),
    'Jalur Gunung Batur',
    'Toya Bungkah',
    8.90,
    676,
    4.0,
    'hard',
    'Area parkir, pemandu lokal, dan warung di sekitar titik awal; fasilitas puncak dapat berubah.',
    'Rute pergi-pulang menuju puncak Gunung Batur melalui permukaan tanah dan batuan vulkanik.'
  ),
  (
    '20000000-0000-4000-8000-000000000010',
    (select id from public.mountains where slug = 'gunung-kelimutu'),
    'Tiwu Nuwa Muri Koo Fai',
    'Area Parkir Kelimutu',
    2.40,
    150,
    0.8,
    'easy',
    'Area parkir, loket, toilet, dan jalur pandang berpagar.',
    'Jalur pendek dari area parkir taman nasional menuju sudut pandang danau kawah Kelimutu.'
  ),
  (
    '20000000-0000-4000-8000-000000000011',
    (select id from public.mountains where slug = 'gunung-tambora'),
    'Pancasila–Kaldera Tambora',
    'Desa Pancasila',
    41.40,
    2387,
    17.5,
    'extreme',
    'Basecamp, area kemah, dan sumber air musiman; logistik harus dibawa dan dikonfirmasi bersama pemandu.',
    'Rute multi-hari dari Desa Pancasila menuju bibir kaldera Tambora melalui hutan dan sabana.'
  ),
  (
    '20000000-0000-4000-8000-000000000012',
    (select id from public.mountains where slug = 'gunung-prau'),
    'Patak Banteng',
    'Patak Banteng',
    3.50,
    620,
    2.5,
    'hard',
    'Basecamp, registrasi, toilet, warung di titik awal, dan area kemah di punggungan.',
    'Rute pendek dan curam dari Patak Banteng menuju area puncak dan perkemahan Gunung Prau.'
  )
on conflict (mountain_id, name) do update
set
  starting_point = excluded.starting_point,
  distance_km = excluded.distance_km,
  elevation_gain = excluded.elevation_gain,
  estimated_hours = excluded.estimated_hours,
  difficulty = excluded.difficulty,
  facilities = excluded.facilities,
  description = excluded.description;
